name: rimxgo
prot: :8080
debug: true # 开发调试模式
logLevel: info # debug|info|warn|error|fatal|disable
session:
  expires: 3600

redis:
  addr: 127.0.0.1:6379
  password: ''
  database: 0
  poolsize: 10

mysqlDefault:
  uri: root:root@tcp(127.0.0.1:3306)/golang?charset=utf8&loc=Local
  maxIdleConns: 3
  maxOpenConns: 5
